# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecc51ce2fb974a24fe5bb39d1e8970ec3550071141a5f4e12f22d8d7dac887192c752226c25f5312598fa34f01de9f9a4cf46ee6e78f77fc9f06f619ca03c464

test:
  secret_key_base: e262b336a16abd2025c8dade9fe0a33ead1f22e3eb284ffeab1b3ee36cab528e187b66e465082b30d2b222a2e3ae676819f81f06045c572fa8175d54400ac2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
